#!/bin/bash

# This is a function to parse configuration files. The syntax is this:
# write_config "SomeTextToChange" "SubstitutionString" "OutputFile" "Separator"
write_config() {
# If file exists then check each line of the file for a match
if [ -f $3 ]; then
   occur=0
   while read line; do
      found=`echo -e "$line" | awk -F "$4" '{ print $1 }'`
      if [ "$1" == "$found" ] || [ "#$1" == "$found" ]; then
         occur=`expr $occur + 1`
      fi
   done < $3
   repeat="true"
   if [ $occur -ne 0 ]; then
      # If the match is found, then write over the old line
      instance=0
      while read line; do
         found=`echo -e "$line" | awk -F "$4" '{ print $1 }'`
         if [ "$1" == "$found" ] || [ "#$1" == "$found" ]; then
            instance=`expr $instance + 1`
            if [ $instance -eq 1 ]; then
               echo -e "$2" >> /tmp/glis/list.tmp
            else
               [ "$1" == "$found" ] && echo -e "#$line" >> /tmp/glis/list.tmp
               [ "#$1" == "$found" ] && echo -e "$line" >> /tmp/glis/list.tmp
            fi
         else
            echo -e "$line" >> /tmp/glis/list.tmp
         fi
      done < $3
      mv -f /tmp/glis/list.tmp $3
   else         
      # If the match is not found, then write to the end of the file
      headerexist=`grep -c "# This configuration was generated by GLIS" $3`
      [ ${headerexist} -eq 0 ] && echo -e "\n# This configuration was generated by GLIS" >> $3
      echo -e "$2" >> $3
   fi
else
   echo -e "# This configuration was generated by GLIS" > $3
   echo -e "$2" >> $3
fi
}